name: MusicService
version: 1.4.7
description: Provides the ability to stream music.
author: Palisade
website: http://dev.bukkit.org/server-mods/musicservice-play-music-anywhere/

main: blakesteel.MusicService.MusicService
database: false
softdepend: [WorldGuard, Factions, Towny, Regios, iZone]

commands:
  musicservice:
    description: Find music streams on shoutcast by searching.
    usage: Type /<command> to get list of available MusicService commands.
    aliases: [music, m]
    
permissions:
  musicservice.*:
    description: Supports setting of the music stations.
    children:
      musicservice.set: true
      musicservice.reload: true
      musicservice.pick: true
      musicservice.find: true
  musicservice.set:
    description: Set the music URL for this location.
    default: op
  musicservice.reload:
    description: Reload the music at this location.
    default: op
  musicservice.pick:
    description: Pick the music stream produced by the findmusic command.
    default: op
  musicservice.find:
    description: Find music streams on shoutcast by searching.
    default: op
